// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleApplication.Data;

namespace SampleApplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("SampleApplication.Models.Joke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Punchline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Setup")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Joke");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Punchline = "I asked him, What’s the word on the street?",
                            Setup = "Yesterday I saw a guy spill all his Scrabble letters on the road"
                        },
                        new
                        {
                            Id = 2,
                            Punchline = "He was just going through a stage",
                            Setup = "Did you hear about the actor who fell through the floorboards?"
                        },
                        new
                        {
                            Id = 3,
                            Punchline = "He just needed a little space",
                            Setup = "Did you hear about the claustrophobic astronaut?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
